services:
  - type: web
    branch: v7
    name: miaomiao-miya
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    volumes:
      - key: MIAOMIAO_DATA
        path: /home/miaomiao/data
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GH_TOKEN
        value: ""
        required: true
      - key: RENDER_EXTERNAL_VOLUME
        value: /home/miaomiao/data
        required: true